### ISSUE TITLE
Find a wall mount for the Pi and make a mounting plan

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/av-api#103]
Talk to Ken about this.

**Comment by xuther** [comment]
To clarify, this doesn't need to be done by March 7 - but by the end of March.

**Comment by jessemillar** [comment]
Prototype mount found on [Thingiverse](http://www.thingiverse.com/thing:1585924). Printing three for our demo.

**Comment by jessemillar** [comment]
Still need to talk to Ken.
