### ISSUE TITLE
Figure out state request commands to the endpoints

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#120]
We need to figure out how we format and handle requests about state to client devices.

**Comment by jessemillar** [comment]
I'm a bit lost. Elaborate?

**Comment by xuther** [comment]
Currently in the database we have a list of commands viable for each device taking the form of:
`<Microservice Address>+<Endpoint>`  
Where the endpoint can be parameterized.

This works great for the RPC commands where we fire them, and then aren't trying to get results back or display them to the users. However when we are querying for state we need a way to say "this is how you get the power state of device X, and when you get it, put it in Y position of the body to return"

Essentially something that does this translation

```
Request for State --> Properties --> Request to Microservice --> Aggregation of responses --> return to user.
                                                    --> Request to Microsergice --> 
                                                    --> Request to Microservice --> 
``` 

Our current format doesn't suuport this.
