### ISSUE TITLE
fix accessors.GetAllRooms in configuration-database-microservice

### ISSUE THREAD

**Issue by c-Monster** [byuoitav/av-api#180]
why do we query ``SELECT * FROM Buildings``?

**Comment by c-Monster** [comment]
Is there a reason we only query production rooms?

**Comment by jessemillar** [comment]
@c-Monster Laziness. We made the dev/stage/production change hastily and haven't proliferated it through the codebase yet. We'll have to have a team discussion about how we want to handle querying dev and stage rooms.
