### ISSUE TITLE
Conditional GUI Selection

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#215]
We need to be able to select the GUI based on some sort of conditions (room configuration, PI role, etc)

**Comment by dannyrandall** [comment]
Solved by https://github.com/byuoitav/touchpanel-ui-microservice/commit/26567c6edfd0072fd75f04828d84efba40b6ccfc. We conditionally select a UI to display based on its [ui-configuration](https://github.com/byuoitav/ui-configuration), and that UI will be displayed.
