### ISSUE TITLE
Create Testing branch in all microservices

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#272]
- [x] Av-API
- [x] Configuration Database Microservice
- [x] Router
- [x] Translator
- [x] ADCP
- [x] Sony
- [x] PJ Link
- [x] Touchpanel UI

Branch from master.

**Comment by dannyrandall** [comment]
- [] Av-API
- [] Configuration Database Microservice
- [] Router
- [] Translator
- [] ADCP
- [] Sony
- [] PJ Link
- [] Touchpanel UI
