### ISSUE TITLE
Figure out why rooms aren't turning off at night. 

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#357]
Some rooms aren't turning off properly at night. Sometimes this is due to the script not running, but there seems to be something else going on.

- [ ] HBLL-4740B
- [ ] ITB-1108-*
- [ ] TLRB-176
- [ ] MSRB-150
- [ ] ITB-3024

**Comment by xuther** [comment]
output for the nightly script gets dumped to `/var/log/rebootapi`

**Comment by cjreeder** [comment]
Found an issue were state was not being applied on reboot of service so there were plenty of devices that didn't have the cron job.  I've pushed state but also updated the Minion files of all PIs so that they will resync.

**Comment by xuther** [comment]
I believe the issue was related to the mis-configuration of the rooms in question where we forgot to define the power states for each display. This field is only used for room-wide power commands, which is why it was almost never used in these single display classrooms and the issue was not found earlier.

We've fixed them and will monitor to ensure that all displays are properly turning off.
