### ISSUE TITLE
Figure out how to handle Video/Audio switchers

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#91]
* We need to handle the case where changeInput for a device goes to a separate device (video switcher) 
* This should probably be a new commandEvaluator.

**Comment by jessemillar** [comment]
Make sure we split out the default change input.

**Comment by xuther** [comment]
This is more or less finished - need to fix the [crestron](https://github.com/byuoitav/crestron-control-microservice) microservice so we can test and merge in the [branch]{https://github.com/byuoitav/av-api/tree/Change-Video-Input-Videoswitcher}.

**Comment by xuther** [comment]
This has been fixed and merged.
