### ISSUE TITLE
Figure out input control

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#93]
We need to decide how we're going to figure out input control.

**Comment by xuther** [comment]
We have a couple of options:

1. We add it to the AV-API Microservice (as it currently stands)
         * This has the benefit of having the AV-API be the 'one-stop-shop' for everything. However this also means that we're obligated to add RPC elements to the API. 
1. We create a second microservice to handle input control and the AV-API becomes a 'family of APIs' to control the room. 
        * we're still obligated to have some sort of RPC elements in the API as a whole, but they're compartmentalized into different microservices. This keeps things clean and cohesive and doesn't lock us into one definition or another of 'input device'. We can front the whole thing with WSO2 for other developers (those developing against our api) and we can just aggregate them using whatever front end system we end up using on the pis or for administration locally. 
      * With this approach we can still leverage the microservices that are backing the AV-API (i.e. the new service can still use the crestron-control-microservice), so we won't be duplicating code. 

Jesse and I are in favor of (2) - It still mandates a significant amount of work, but will at least silo that work from the A/V device control we currently have working. (This also means that we don't have to run ALL the code in every room, Tec Lites for example have no need of the input control service). 

Thoughts?

**Comment by jessemillar** [comment]
I very much am on board with **option 2**. I like the concept of a "family of APIs" and if we need a "one-stop-shop" at any point that "shop" won't be the same for every group. E.g. Ken's group will need a different interface ("shop") for testing rooms holistically than users will need for writing apps or using the in-room touchpanels.

**Comment by xuther** [comment]
In the meeting with Scott yesterday this was pushed back to the back-burner as not being necessary for either of the march deadlines - though it may need to be addressed in phase 2. 

Essentially we don't need to worry about set top boxes or Blu-Ray players for now however the plans for fixing the [projector control](https://github.com/byuoitav/av-api/issues/94) are moving ahead in the [AV-API-RPC](https://github.com/byuoitav/av-api-rpc)

We do need to have a discussion about what the RESTFUL input devices will be generalized towards when this does happen.

**Comment by danclegg** [comment]
I agree with the preference of option 2. 

@xuther Can you clarify this?

> We do need to have a discussion about what the RESTFUL input devices will be generalized towards when this does happen.

**Comment by xuther** [comment]
@danclegg For sure!

I just want to make sure that at some point we have a discussion about 
1. If we're going to control RESTFUL input devices through the `AV-API` microservice
1. If yes, what do we want the standard set of attributes exposed to look like? 
1. If no, will we handle that through a separate top-level microservice? Or just not worry at all. A

So if someday we get a device that controls input (an AppleTV for example) that does allow us to set state, and we decide we need to control it, how do we approach that, architecturally. 

The issue as I see it is that we don't necessarily have a standard set of properties common to all input devices beyond maybe power control. With Displays we know that **every** display we have 
* Inputs
* Power State
* Blanking 

So those are the attributes we expose. Similar for audio devices, we know that **every** audio device will have:
*Inputs 
* Power State
* Volume 
* Muting

So those are the attributes we expose. The question is - what are those common attributes for REST-ful input devices, if any. And if there aren't any, how do we want to handle that. 

@danielwells does that about sum up our discussions we've had on the subject?

**Comment by dannyrandall** [comment]
No more DMPS'.

**Comment by jessemillar** [comment]
Wait. No more DMPS? What do you mean? The system doesn't interface with them anymore or BYU isn't using them at all? #curious

**Comment by dannyrandall** [comment]
No more crestron. All rooms where the pi is being installed are being designed without their control system. PI RULES ALL

**Comment by jessemillar** [comment]
@dannyrandall That's awesome news! We pushed pretty hard for that when I was still there!
