### ISSUE TITLE
Audio control of Projectors

### ISSUE THREAD

**Issue by xuther** [byuoitav/av-api#94]
Figure out how to control audio in the projectors.

**Comment by xuther** [comment]
Audio switches with the display today. The *main* issue is the volume control.

**Comment by xuther** [comment]
After an investigation into the PJ Talk (sony PJ Link) it looks like PJ Talk V1 supported volume, but V2 does not. (here's the v2 documentation https://docs.sony.com/release/VW100_protocol.pdf) and V2 is the version run by the sony projector we have. 

The original decision was made to use London devices (Or some other ip controllable audio devices), however it was determined that this may not be viable for all the tec lite rooms. The Sony Projectors do use a CGI interface in their webpage to control certain aspects (volume), however this control is state-less (it replicates a remote). 

Our thought that this can be connected to [issue 93](https://github.com/byuoitav/av-api/issues/93) - control of stateless devices). We've decided to go ahead and create a second top-level micro-service to handle stateless device, and a CGI micro-service on the backend to handle the volume interaction with the Projectors.

**Comment by xuther** [comment]
@danclegg - thoughts? @danielwells?

**Comment by danclegg** [comment]
@xuther Why were IP-controlled DSPs non-viable for most (if not all) TEC Lite rooms?

I see that we _have_ to move ahead in this way, but it doesn't feel very clean.

**Comment by jessemillar** [comment]
I believe our current understanding is that not all TEC Lite rooms have a DSP and we weren't wanting to put a London in every TEC Lite room which mandated the move. Correct me if I'm wrong.

**Comment by danielwells** [comment]
Part of the reason we were willing to go forward with this approach was because it could help lay the groundwork for / test the "stateless source control" architecture we discussed.

**Comment by c-Monster** [comment]
The RPC version of the API and CGI microservices are complete.
