### ISSUE TITLE
Update Pi UI

### ISSUE THREAD

**Issue by jessemillar** [byuoitav/av-api#98]

**Comment by dgrandall** [comment]
- [ ] change video input
- [ ] change audio input
- [ ] blank the display
- [ ] change the volume
- [ ] mute the audio
- [ ] turn the device on/off

**Comment by jessemillar** [comment]
As a note, just because the current UI currently has buttons for some of these actions doesn't mean they're hitting the correct endpoints when pressed. We've rewritten pretty much everything about the API since the initial UI.
